version: '3.3'

services:
  db:
    image: postgres:latest 
    container_name: postgres-db
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data
    networks:
      - custom-network

  backend:
    image: backend-image:latest 
    container_name: backend-app
    environment:
      DB_HOST: ${DB_HOST} 
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}
      DB_PORT: ${DB_PORT}
      ALLOWED_ORIGINS: ${ALLOWED_ORIGINS}
    ports:
      - "8080:8080"
    depends_on:
      - db
    networks:
      - custom-network 
        
  frontend:
    image: frontend-image:latest 
    container_name: frontend-app
    ports:
      - "3000:80"
    depends_on:
      - backend
    networks:
      - custom-network

networks:
  custom-network:
    driver: bridge

volumes:
  db-data:
